// RPC call states
export const RPC_LOADING = 'RPC_LOADING';
export const RPC_ERROR = 'RPC_ERROR';

//EVENTS

// FETCHING
export const FETCH_PLAYER = 'FETCH_PLAYER';
export const FETCH_RESOURCES = 'FETCH_RESOURCES';
export const FETCH_INVENTORY = 'FETCH_INVENTORY';
export const FETCH_CASTERS = 'FETCH_CASTERS';

// INSTRUCTIONS
export const INST_INIT_PLAYER = 'INST_INIT_PLAYER';
export const INST_INIT_LADA_ACCOUNT = 'INST_INIT_LADA_ACCOUNT';
export const INST_INIT_RES_ACCOUNT = 'INST_INIT_RES_ACCOUNT';
export const INST_INIT_CASTER = 'INST_INIT_CASTER';
export const INST_CRANK = 'INST_CRANK';
export const INST_OPEN_CHEST = 'INST_OPEN_CHEST';
export const INST_MANUAL_RES_BURN = 'INST_MANUAL_RES_BURN';
export const INST_COMMIT_MOVE = 'INST_COMMIT_MOVE';
export const INST_COMMIT_CRAFT = 'INST_COMMIT_CRAFT';
export const INST_COMMIT_SPELL = 'INST_COMMIT_SPELL';
export const INST_COMMIT_LOOT = 'INST_COMMIT_LOOT';
export const INST_REDEEM_ACTION = 'INST_REDEEM_ACTION';
export const INST_EQUIP = 'INST_EQUIP';
export const INST_UNEQUIP = 'INST_UNEQUIP';
export const INST_REDEEM_CASTER = 'INST_REDEEM_CASTER';
export const INST_REDEEM_ITEM = 'INST_REDEEM_ITEM';
export const INST_MINT_NFT = 'INST_MINT_NFT';
export const INST_BURN_NFT = 'INST_BURN_NFT';
// RPC Connections
export const CONNECT_RPC = 'CONNECT_RPC';

// ERRORS
export const RATE_LIMIT = 'RATE_LIMIT';

// DEBUG INSTRUCTIONS
export const GIVE_LADA = 'GIVE_LADA';
export const GIVE_RESOURCES = 'GIVE_RESOURCES';
export const GIVE_ITEM = 'GIVE_ITEM';
export const CHANGE_TILE = 'CHANGE_TILE';
